In [4]:
import numpy as np

a = np.arange(16)
b = a.reshape((4,4))
print(b)
# print(b[:,1])
print(b.argmax(0))
print(b.max(0))

print(b.argmax(1))
print(b.max(1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[3 3 3 3]
[12 13 14 15]
[3 3 3 3]
[ 3  7 11 15]


In [2]:
a,b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [4]:
print(b)
print(np.sum(b, axis=1, keepdims=True))
print(np.sum(b, axis=0, keepdims=True).T)
print(np.sum(b, axis=1, keepdims=True))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 6]
 [22]
 [38]
 [54]]
[[24]
 [28]
 [32]
 [36]]
[[ 6]
 [22]
 [38]
 [54]]


In [5]:
index_max = b.argmax() # 15
index_max_axis_1 = b.argmax(1) # array([3, 3, 3, 3]),按列取最大值索引

In [6]:
import numpy as np
a =np.array([0,0,0,2,1,1,1,1,2])
print(a)
c = a + 1
print(np.bincount(a))
print(np.bincount(a).argmax())
print(np.bincount(a)[np.bincount(a).argmax()])

# print(np.bincount(c))
# print(np.bincount(c).argmax())


[0 0 0 2 1 1 1 1 2]
[3 4 2]
1
4


In [7]:
import numpy as np 
 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
print (y)

[1 4 5]


In [8]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
y = x[...,  [0,1,0]]  
print (y)

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [13]:
x = np.arange(40).reshape((8,5))
y = np.arange(20).reshape((4,5))
print(x,y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
x.dot(y.T)

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455],
       [ 230,  780, 1330, 1880],
       [ 280,  955, 1630, 2305],
       [ 330, 1130, 1930, 2730],
       [ 380, 1305, 2230, 3155]])

In [15]:
x@y.T

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455],
       [ 230,  780, 1330, 1880],
       [ 280,  955, 1630, 2305],
       [ 330, 1130, 1930, 2730],
       [ 380, 1305, 2230, 3155]])

In [16]:
a = np.arange(15).reshape((5,3))
l = np.split(a,5)
l

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]])]

In [20]:
for i in range(5):
    c = l[i]
    # d = np.concatenate(*l[0:i],*l[i+1,5])
    # print(c,d)
    print(*l[0:i])


[[0 1 2]]
[[0 1 2]] [[3 4 5]]
[[0 1 2]] [[3 4 5]] [[6 7 8]]
[[0 1 2]] [[3 4 5]] [[6 7 8]] [[ 9 10 11]]


In [11]:
import numpy as np
x= np.ones((3,5))
y = np.arange(10).reshape((5,2))
print(x)
print(y)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
c = x.dot(y)
c
y[1].reshape(2)


array([2, 3])

# 矩阵乘法
## X.dot(W)

In [1]:
import numpy as np 
shape = (5,5)
X = np.ones(shape)
W = np.arange(25).reshape(shape)
print(X.dot(W))
print(X@W)
print(np.multiply(X,W))


[[50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]]
[[50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]
 [50. 55. 60. 65. 70.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [3]:
W

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])